language: node_js
sudo: required

services:
  - docker

node_js:
  - 10

env:
  - IMAGE_NAME=instantbox/instantbox-frontend

cache: npm

install:
  - npm ci

script:
  - npm run lint && npm test
  - docker pull "$IMAGE_NAME" || true
  - docker build --cache-from "$IMAGE_NAME" 
      --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" 
      --build-arg VCS_REF="$TRAVIS_COMMIT" 
      -t "build/$IMAGE_NAME" -f ./Dockerfile .
  - docker run -d -P --name temp "build/$IMAGE_NAME"
  - docker rm -f temp || true
  
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD_SECURE";
      docker tag "build/$IMAGE_NAME" "$IMAGE_NAME";
      docker push "$IMAGE_NAME";
    fi
  - if [[ -n "$TRAVIS_TAG" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD_SECURE";
      docker tag "build/$IMAGENAME" "$IMAGENAME:$TRAVIS_TAG";
      docker push "$IMAGE_NAME:$TRAVIS_TAG";
    fi
